SOURCE=showertray.scad
DEPENDS=hsu.scad Makefile.showertray

OPENSCADOPTIONS=--backend=manifold --enable textmetrics -D debug=0

all: showertray.stl

showertray.stl: $(SOURCE) $(DEPENDS)
	openscad $(OPENSCADOPTIONS) -D print=1 -o $@ $(SOURCE)
	echo $@ built.

