SOURCE=diskrewriterstand.scad
DEPENDS=hsu.scad Makefile.diskrewriterstand
IMAGES=
ALL=diskrewriterdiskholder35.stl diskrewriterbase.stl lockcliptest.stl

OPENSCADOPTIONS=--backend=manifold --enable textmetrics -D debug=0

all: $(ALL)

dist: diskrewriterstand.zip

diskrewriterstand-source-distribution.zip: $(SOURCE) $(DEPENDS)
	rm -rf diskrewriterstand-distribution
	rm -f diskrewriterstand-distribution.zip
	mkdir -p diskrewriterstand-distribution
	cp $(SOURCE) $(DEPENDS) diskrewriterstand-distribution
	zip -r $@ diskrewriterstand-distribution
	echo $@ built.      

diskrewriterstand-full-distribution.zip: $(ALL) $(SOURCE) $(DEPENDS) $(IMAGES)
	rm -rf diskrewriterstand-distribution
	rm -f diskrewriterstand-distribution.zip
	mkdir -p diskrewriterstand-distribution
	cp $(ALL) $(SOURCE) $(DEPENDS) $(IMAGES) diskrewriterstand-distribution
	zip -r $@ diskrewriterstand-distribution
	echo $@ built.      

clean:
	rm $(ALL)

diskrewriterdiskholder35.stl: $(SOURCE) $(DEPENDS)
	openscad $(OPENSCADOPTIONS) -D print=1 -o $@ $(SOURCE)
	echo $@ built.

diskrewriterbase.stl: $(SOURCE) $(DEPENDS)
	openscad $(OPENSCADOPTIONS) -D print=2 -o $@ $(SOURCE)
	echo $@ built.

lockcliptest.stl: $(SOURCE) $(DEPENDS)
	openscad $(OPENSCADOPTIONS) -D print=3 -o $@ $(SOURCE)
	echo $@ built.

