SOURCE=casespare.scad
DEPENDS=hsu.scad Makefile.casespare
IMAGES=
ALL=casespare.stl casesparebase.stl casespareclips.stl casesparetapeclip.stl

OPENSCADOPTIONS=-D debug=0 --backend=manifold --enable textmetrics

all: $(ALL)

dist: casespare.zip

casespare-source-distribution.zip: $(SOURCE) $(DEPENDS)
	rm -rf casespare-distribution
	rm -f casespare-distribution.zip
	mkdir -p casespare-distribution
	cp $(SOURCE) $(DEPENDS) casespare-distribution
	zip -r $@ casespare-distribution
	echo $@ built.      

casespare-full-distribution.zip: $(ALL) $(SOURCE) $(DEPENDS) $(IMAGES)
	rm -rf casespare-distribution
	rm -f casespare-distribution.zip
	mkdir -p casespare-distribution
	cp $(ALL) $(SOURCE) $(DEPENDS) $(IMAGES) casespare-distribution
	zip -r $@ casespare-distribution
	echo $@ built.      

clean:
	rm $(ALL)

casesparebase.stl: $(SOURCE) $(DEPENDS)
	openscad $(OPENSCADOPTIONS) -D print=1 -o $@ $(SOURCE)
	echo $@ built.

casespareclips.stl: $(SOURCE) $(DEPENDS)
	openscad $(OPENSCADOPTIONS) -D print=2 -o $@ $(SOURCE)
	echo $@ built.

casesparetapeclip.stl: $(SOURCE) $(DEPENDS)
	openscad $(OPENSCADOPTIONS) -D print=3 -o $@ $(SOURCE)
	echo $@ built.

casespare.stl: $(SOURCE) $(DEPENDS)
	openscad $(OPENSCADOPTIONS) -D print=4 -o $@ $(SOURCE)
	echo $@ built.

