SOURCE=lattialista.scad

all: lattialistakeittio.stl lattialistaeteinen.stl lattialistabackplate.stl lattialistakulmapala.stl

lattialistakeittio.stl: $(SOURCE)
	openscad -D print=1 -o $@ $(SOURCE)
	echo $@ built.

lattialistaeteinen.stl: $(SOURCE)
	openscad -D print=2 -o $@ $(SOURCE)
	echo $@ built.

lattialistabackplate.stl: $(SOURCE)
	openscad -D print=3 -D strong=1 -o $@ $(SOURCE)
	echo $@ built.

lattialistakulmapala.stl: $(SOURCE)
	openscad -D print=5 -o $@ $(SOURCE)
	echo $@ built.

