SOURCE=berrycleaner.scad
DEPENDS=hsu.scad Makefile.berrycleaner

all: berrycleanerbottom.stl berrycleanertop.stl

berrycleanertop.stl: $(SOURCE) $(DEPENDS)
	openscad -D print=1 -o $@ $(SOURCE)
	echo $@ built.

berrycleanerbottom.stl: $(SOURCE) $(DEPENDS)
	openscad -D print=2 -o $@ $(SOURCE)
	echo $@ built.

